const PRODUTOS = [
  {
    id: 1,
    brand: "Asics",
    name: "Asics Gel NYC Branco",
    price: 899.9,
    oldPrice: 1099.9,
    description: "Inspirado no estilo Y2K. Versão clara que mistura silhuetas de corrida com tecnologia avançada para máximo conforto urbano.",
    badge: "Trending",
    category: "Lifestyle",
    featured: true,
    rating: 4.8,
    reviews: 142,
    sizes: [38, 39, 40, 41, 42, 43],
    colors: [{ name: "Branco", hex: "#f8fafc" }],
    images: ["../images/shoes/ASICS-GEL-NYC-b.png", "../images/shoes/ASICS-GEL-NYC-b2.png"],
    reviewsList: [{ author: "Gabriel C.", rating: 5, comment: "Estilo retro perfeito e macio.", date: "05/04/2026" }]
  },
  {
    id: 2,
    brand: "Asics",
    name: "Asics Gel NYC Branco e Preto",
    price: 899.9,
    oldPrice: 1099.9,
    description: "Inspirado no estilo Y2K. Contraste marcante com painéis pretos sobrepostos.",
    badge: "Hype",
    category: "Lifestyle",
    featured: false,
    rating: 4.8,
    reviews: 94,
    sizes: [38, 39, 40, 41, 42, 43],
    colors: [{ name: "Branco/Preto", hex: "#d1d5db" }],
    images: ["../images/shoes/ASICS-GEL-NYC-bp.png"],
    reviewsList: [{ author: "Matias T.", rating: 5, comment: "Excelente para o dia a dia.", date: "10/04/2026" }]
  },
  {
    id: 3,
    brand: "Asics",
    name: "Asics Gel NYC Preto e Cinza",
    price: 899.9,
    oldPrice: 1099.9,
    description: "Inspirado no estilo Y2K. Versão furtiva e elegante para a noite.",
    badge: "Novo",
    category: "Lifestyle",
    featured: false,
    rating: 4.7,
    reviews: 55,
    sizes: [38, 39, 40, 41, 42, 43],
    colors: [{ name: "Preto/Cinza", hex: "#374151" }],
    images: ["../images/shoes/ASICS-GEL-NYC-pc.png"],
    reviewsList: [{ author: "Lucas F.", rating: 4, comment: "Gostei muito da discrição dessa cor.", date: "08/04/2026" }]
  },
  {
    id: 4,
    brand: "Adidas",
    name: "Adizero Evo SL Azul",
    price: 1299.9,
    oldPrice: 1499.9,
    description: "A super leveza do Adizero em cor vibrante para propulsão em treinos.",
    badge: "Pro",
    category: "Corrida",
    featured: true,
    rating: 4.9,
    reviews: 86,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: [{ name: "Azul", hex: "#3b82f6" }],
    images: ["../images/shoes/Adizero-Evo-Sl-A.png", "../images/shoes/Adizero-Evo-Sl-A2.png", "../images/shoes/Adizero-Evo-Sl-A3.png", "../images/shoes/Adizero-Evo-Sl-A4.png", "../images/shoes/Adizero-Evo-Sl-A5.png"],
    reviewsList: [{ author: "Marcelo L.", rating: 5, comment: "Cor linda e tênis rápido demais.", date: "02/04/2026" }]
  },
  {
    id: 5,
    brand: "Adidas",
    name: "Adizero Evo SL Branco",
    price: 1299.9,
    oldPrice: 1499.9,
    description: "A super leveza do Adizero na versão clássica e purista Branca.",
    badge: "Pro",
    category: "Corrida",
    featured: false,
    rating: 4.8,
    reviews: 120,
    sizes: [39, 40, 41, 42, 43, 44],
    colors: [{ name: "Branco", hex: "#f8fafc" }],
    images: ["../images/shoes/Adizero-Evo-Sl-b.png", "../images/shoes/Adizero-Evo-Sl-b2.png", "../images/shoes/Adizero-Evo-Sl-b3.png", "../images/shoes/Adizero-Evo-Sl-b4.png", "../images/shoes/Adizero-Evo-Sl-b5.png", "../images/shoes/Adizero-Evo-Sl-b6.png"],
    reviewsList: [{ author: "Carlos M.", rating: 5, comment: "Perfeito para minhas provas de 10k.", date: "09/04/2026" }]
  },
  {
    id: 6,
    brand: "Nike",
    name: "Air Max DN8 All Night",
    price: 999.9,
    oldPrice: 1199.9,
    description: "Edição All Night. Sistema Dynamic Air para conforto furtivo noturno.",
    badge: "Novo",
    category: "Lifestyle",
    featured: true,
    rating: 4.9,
    reviews: 320,
    sizes: [38, 39, 40, 41, 42],
    colors: [{ name: "All Night", hex: "#111827" }],
    images: ["../images/shoes/Air-Max-Dn8-All-Night.png"],
    reviewsList: [{ author: "Tiago S.", rating: 5, comment: "Estilo absurdo no rolê noturno.", date: "11/04/2026" }]
  },
  {
    id: 7,
    brand: "Nike",
    name: "Air Max DN8 Branco",
    price: 999.9,
    oldPrice: 1199.9,
    description: "A próxima geração Air. Variante branca super limpa e moderna.",
    badge: "Clean",
    category: "Lifestyle",
    featured: false,
    rating: 4.7,
    reviews: 140,
    sizes: [38, 39, 40, 41, 42, 43],
    colors: [{ name: "Branco", hex: "#f8fafc" }],
    images: ["../images/shoes/Air-Max-Dn8-b.png"],
    reviewsList: [{ author: "Luisa F.", rating: 5, comment: "Muito confortável e branco brilhante.", date: "04/04/2026" }]
  },
  {
    id: 8,
    brand: "Nike",
    name: "Air Max DN8 Cinza e Preto",
    price: 999.9,
    oldPrice: 1199.9,
    description: "Variante neutra impecável para combinações versáteis no dia a dia.",
    badge: "Trending",
    category: "Lifestyle",
    featured: false,
    rating: 4.6,
    reviews: 80,
    sizes: [39, 40, 41, 42, 43],
    colors: [{ name: "Cinza/Preto", hex: "#4b5563" }],
    images: ["../images/shoes/Air Max DN8-cp.png"],
    reviewsList: [{ author: "Fernando O.", rating: 4, comment: "Bom pro trampo.", date: "10/04/2026" }]
  },
  {
    id: 9,
    brand: "Nike",
    name: "Air Max DN8 Laranja e Preto",
    price: 999.9,
    oldPrice: 1199.9,
    description: "Variante explosiva laranja e preto para máximo impacto visual.",
    badge: "Hot",
    category: "Lifestyle",
    featured: false,
    rating: 4.8,
    reviews: 215,
    sizes: [38, 39, 40, 41, 42, 43],
    colors: [{ name: "Laranja", hex: "#f97316" }],
    images: ["../images/shoes/Air-Max-Dn8-lp.png", "../images/shoes/Air-Max-Dn8-lp-a.png"],
    reviewsList: [{ author: "Rafael G.", rating: 5, comment: "Chama atenção de longe!", date: "03/04/2026" }]
  },
  {
    id: 10,
    brand: "Nike",
    name: "Air Max DN8 Preto",
    price: 999.9,
    oldPrice: 1199.9,
    description: "Edição essencial preto com sutis contrastes esportivos.",
    badge: "Clássico",
    category: "Lifestyle",
    featured: false,
    rating: 4.7,
    reviews: 130,
    sizes: [38, 39, 40, 41, 42],
    colors: [{ name: "Preto", hex: "#1f2937" }],
    images: ["../images/shoes/Air-Max-Dn8-p.jpg"],
    reviewsList: [{ author: "André M.", rating: 4, comment: "Básico e muito potente.", date: "12/04/2026" }]
  },
  {
    id: 11,
    brand: "Nike",
    name: "Air Force 1 Ambush",
    price: 1399.9,
    oldPrice: 1599.9,
    description: "Colaboração ousada. O Swoosh exagerado e cores que rementem a velocidade.",
    badge: "Collab",
    category: "Lifestyle",
    featured: true,
    rating: 4.8,
    reviews: 95,
    sizes: [38, 39, 40, 41, 42, 43],
    colors: [{ name: "Branco/Preto", hex: "#d1d5db" }],
    images: ["../images/shoes/Air-Force-ambush-bc.png"],
    reviewsList: [{ author: "Leo M.", rating: 5, comment: "Exclusivo demais.", date: "12/04/2026" }]
  },
  {
    id: 12,
    brand: "Nike",
    name: "Air Force 1 Branco Puro",
    price: 799.9,
    oldPrice: 999.9,
    description: "O Air Force 1 na sua glória e cor original toda branca. Simples. Atemporal.",
    badge: "Ícone",
    category: "Lifestyle",
    featured: false,
    rating: 5.0,
    reviews: 5320,
    sizes: [38, 39, 40, 41, 42, 43],
    colors: [{ name: "Branco", hex: "#ffffff" }],
    images: ["../images/shoes/air-force-1-b.png"],
    reviewsList: [{ author: "Julia P.", rating: 5, comment: "Clássico é clássico.", date: "15/04/2026" }]
  },
  {
    id: 13,
    brand: "Nike",
    name: "Air Force 1 Branco e Cinza",
    price: 799.9,
    oldPrice: 999.9,
    description: "Detalhes em cinza dão um visual um pouco mais discreto e diferenciado ao modelo branco.",
    badge: "Lifestyle",
    category: "Casual",
    featured: false,
    rating: 4.8,
    reviews: 310,
    sizes: [38, 39, 40, 41, 42],
    colors: [{ name: "Branco/Cinza", hex: "#d1d5db" }],
    images: ["../images/shoes/Nike-Air-Force-1-b-c.png"],
    reviewsList: [{ author: "Pedro", rating: 5, comment: "Estiloso e fácil de limpar.", date: "10/04/2026" }]
  },
  {
    id: 14,
    brand: "Nike",
    name: "Air Jordan 1 Low Preto e Branco",
    price: 899.9,
    oldPrice: 1099.9,
    description: "Silhueta clássica do Jordan com predominância preta e toques em branco conhecidos como Panda.",
    badge: "Hype",
    category: "Lifestyle",
    featured: true,
    rating: 4.9,
    reviews: 1450,
    sizes: [38, 39, 40, 41, 42, 43],
    colors: [{ name: "Preto/Branco", hex: "#111827" }],
    images: ["../images/shoes/Air-Jordan-1-Low-pb.png"],
    reviewsList: [{ author: "Caio A.", rating: 5, comment: "Básico que combina com tudo.", date: "11/04/2026" }]
  },
  {
    id: 15,
    brand: "Nike",
    name: "Air Jordan 1 Low Branco e Preto",
    price: 899.9,
    oldPrice: 1099.9,
    description: "A inversão de cores focada no cabedal mais claro.",
    badge: "Clássico",
    category: "Lifestyle",
    featured: false,
    rating: 4.8,
    reviews: 620,
    sizes: [39, 40, 41, 42, 43],
    colors: [{ name: "Branco/Preto", hex: "#f3f4f6" }],
    images: ["../images/shoes/Air-Jordan-1-Low-bp.png"],
    reviewsList: [{ author: "Igor Z.", rating: 4, comment: "Muito clean.", date: "01/04/2026" }]
  },
  {
    id: 16,
    brand: "Nike",
    name: "Air Jordan 1 Low Sail",
    price: 899.9,
    oldPrice: 1099.9,
    description: "Sofisticado ton-sur-ton Sail Soft Pearl que abraça a moda neutra.",
    badge: "Elegante",
    category: "Lifestyle",
    featured: false,
    rating: 4.9,
    reviews: 410,
    sizes: [37, 38, 39, 40, 41],
    colors: [{ name: "Sail", hex: "#e5e7eb" }],
    images: ["../images/shoes/air-jordan1-low-sail-soft-pearl-b.png"],
    reviewsList: [{ author: "Karina M.", rating: 5, comment: "Perfeito, lindo ton pastel.", date: "13/04/2026" }]
  },
  {
    id: 17,
    brand: "Nike",
    name: "Court Borough Mid 2",
    price: 499.9,
    oldPrice: 599.9,
    description: "Design inspirado no basquete de cano médio. Oferece estilo retrô urbano e proteção.",
    badge: "Retro",
    category: "Casual",
    featured: false,
    rating: 4.6,
    reviews: 320,
    sizes: [38, 39, 40, 41, 42],
    colors: [{ name: "Branco", hex: "#f8fafc" }],
    images: ["../images/shoes/Court-Borough-Mid-2.png"],
    reviewsList: [{ author: "Lucas A.", rating: 4, comment: "Esquenta um pouquinho a canela, bem estiloso.", date: "08/04/2026" }]
  },
  {
    id: 18,
    brand: "Puma",
    name: "Mercedes AMG Petronas F1 Branco",
    price: 599.9,
    oldPrice: 799.9,
    description: "Variação majoritariamente branca inspirada na pureza e na aerodinâmica automobilística.",
    badge: "Motorsport",
    category: "Casual",
    featured: false,
    rating: 4.8,
    reviews: 140,
    sizes: [39, 40, 41, 42, 43],
    colors: [{ name: "Branco", hex: "#f8fafc" }],
    images: ["../images/shoes/Mercedes-AMG-Petronas-F1-ba.png", "../images/shoes/Mercedes-AMG-Petronas-F1-ba2.png", "../images/shoes/Mercedes-AMG-Petronas-F1-ba3.png", "../images/shoes/Mercedes-AMG-Petronas-F1-ba4.png"],
    reviewsList: [{ author: "Eduardo S.", rating: 5, comment: "Pareço piloto saindo na rua.", date: "09/04/2026" }]
  },
  {
    id: 19,
    brand: "Puma",
    name: "Mercedes AMG Petronas F1 Preto",
    price: 599.9,
    oldPrice: 799.9,
    description: "Fibra de carbono e visual implacável neste F1 totalmente preto.",
    badge: "Motorsport",
    category: "Casual",
    featured: false,
    rating: 4.7,
    reviews: 210,
    sizes: [39, 40, 41, 42, 43],
    colors: [{ name: "Preto", hex: "#111827" }],
    images: ["../images/shoes/Mercedes-AMG-Petronas-F1-p.jpg", "../images/shoes/Mercedes-AMG-Petronas-F1-p2.jpg"],
    reviewsList: [{ author: "Marcos T.", rating: 5, comment: "Mto bom. Encaixe perfeito no pé.", date: "10/04/2026" }]
  },

  {
    id: 21,
    brand: "Puma",
    name: "Suede Classic Preto",
    price: 399.9,
    oldPrice: 499.9,
    description: "O modelo de rua mais atemporal. Material em camurça super macio.",
    badge: "Best Seller",
    category: "Casual",
    featured: false,
    rating: 4.9,
    reviews: 2150,
    sizes: [37, 38, 39, 40, 41, 42],
    colors: [{ name: "Preto", hex: "#111827" }],
    images: ["../images/shoes/Puma Suede Classic-p.png"],
    reviewsList: [{ author: "João P.", rating: 5, comment: "Clássico.", date: "15/03/2026" }]
  },
  {
    id: 22,
    brand: "Adidas",
    name: "Forum 84 Low Branco",
    price: 799.9,
    oldPrice: 999.9,
    description: "Tênis de basquete dos anos 80 agora em versão limpa branca para dia a dia.",
    badge: "Originals",
    category: "Lifestyle",
    featured: false,
    rating: 4.8,
    reviews: 642,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: [{ name: "Branco Vintage", hex: "#f1f5f9" }],
    images: ["../images/shoes/adidas-forum-84-low-b.png"],
    reviewsList: [{ author: "Roberto L.", rating: 5, comment: "Qualidade de couro Premium.", date: "09/04/2026" }]
  },
  {
    id: 23,
    brand: "Nike",
    name: "Air Max DN Branco",
    price: 999.9,
    oldPrice: 1199.9,
    description: "Dynamic Air com tubos de energia na colorway mais limpa.",
    badge: "Tech",
    category: "Lifestyle",
    featured: true,
    rating: 4.7,
    reviews: 120,
    sizes: [38, 39, 40, 41, 42],
    colors: [{ name: "Branco", hex: "#ffffff" }],
    images: ["../images/shoes/air-max-dn-b.png", "../images/shoes/air-max-dn-b2.png", "../images/shoes/air-max-dn-b3.png", "../images/shoes/air-max-dn-b4.png"],
    reviewsList: [{ author: "Samara", rating: 4, comment: "Amortecimento perfeito e lindo.", date: "01/04/2026" }]
  },
  {
    id: 24,
    brand: "Nike",
    name: "Air Max Plus TN Preto",
    price: 1199.9,
    oldPrice: 1299.9,
    description: "A gaiola TPU lendária de barbatana de tubarão na versão Triple Black.",
    badge: "Hype",
    category: "Lifestyle",
    featured: false,
    rating: 4.8,
    reviews: 432,
    sizes: [39, 40, 41, 42, 43],
    colors: [{ name: "Preto", hex: "#000000" }],
    images: ["../images/shoes/Air Max Plus Black-p.png", "../images/shoes/air-max-tn-p.png"],
    reviewsList: [{ author: "Anderson B.", rating: 5, comment: "Estética bandida.", date: "07/04/2026" }]
  },
  {
    id: 25,
    brand: "Nike",
    name: "Air Max Plus TN Branco",
    price: 1199.9,
    oldPrice: 1299.9,
    description: "Contraste vibrante nas hastes inspiradas em palmeiras com o material branco.",
    badge: "Exclusivo",
    category: "Lifestyle",
    featured: false,
    rating: 4.7,
    reviews: 154,
    sizes: [39, 40, 41, 42, 43],
    colors: [{ name: "Branco", hex: "#f8fafc" }],
    images: ["../images/shoes/air-max-tn-plus-b.png", "../images/shoes/air-max-tn-plus-b2.png"],
    reviewsList: [{ author: "Rodrigo", rating: 5, comment: "Top.", date: "12/04/2026" }]
  },
  {
    id: 26,
    brand: "New Balance",
    name: "New Balance 9060 Cinza",
    price: 1099.9,
    oldPrice: 1299.9,
    description: "Cor histórica da New Balance na versão futurista 9060.",
    badge: "Heritage",
    category: "Lifestyle",
    featured: true,
    rating: 4.9,
    reviews: 820,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    colors: [{ name: "Cinza", hex: "#9ca3af" }],
    images: ["../images/shoes/nb-9060-c.png", "../images/shoes/nb-9060-c2.png", "../images/shoes/nb-9060-c3.png", "../images/shoes/nb-9060-c4.png"],
    reviewsList: [{ author: "Larissa T.", rating: 5, comment: "A cor cinza é clássica.", date: "15/04/2026" }]
  },
  {
    id: 27,
    brand: "New Balance",
    name: "New Balance 9060 Preto",
    price: 1099.9,
    oldPrice: 1299.9,
    description: "Look pesadex com visual noturno do y2k.",
    badge: "Trending",
    category: "Lifestyle",
    featured: false,
    rating: 4.8,
    reviews: 140,
    sizes: [38, 39, 40, 41, 42],
    colors: [{ name: "Preto", hex: "#1f2937" }],
    images: ["../images/shoes/nb-9060-p.png", "../images/shoes/nb-9060-p2.png", "../images/shoes/nb-9060-p3.png", "../images/shoes/nb-9060-p4.png"],
    reviewsList: [{ author: "Rony", rating: 4, comment: "Pesado! Muito top.", date: "10/04/2026" }]
  },
  {
    id: 28,
    brand: "New Balance",
    name: "New Balance 9060 Marrom",
    price: 1099.9,
    oldPrice: 1299.9,
    description: "Tons de terra combinam com visuais casuais chiques com sobreposições.",
    badge: "Elegante",
    category: "Lifestyle",
    featured: false,
    rating: 4.9,
    reviews: 70,
    sizes: [39, 40, 41, 42, 43],
    colors: [{ name: "Marrom", hex: "#78350f" }],
    images: ["../images/shoes/nb-9060-m.png"],
    reviewsList: [{ author: "Gabi", rating: 5, comment: "Cor linda demais.", date: "09/04/2026" }]
  },
  {
    id: 29,
    brand: "Nike",
    name: "Nocta Glide Preto",
    price: 1499.9,
    oldPrice: 1699.9,
    description: "Assinado pelo rapper Drake (Nocta). Detalhes espelhados refletindo o hype.",
    badge: "Premium",
    category: "Lifestyle",
    featured: true,
    rating: 4.8,
    reviews: 133,
    sizes: [39, 40, 41, 42, 43],
    colors: [{ name: "Preto", hex: "#111827" }],
    images: ["../images/shoes/nocta-glide-pb.png"],
    reviewsList: [{ author: "Diogo F.", rating: 5, comment: "Luxo puro.", date: "21/03/2026" }]
  }
];

const BRANDS = [...new Set(PRODUTOS.map(p => p.brand))];
const CATEGORIES = [...new Set(PRODUTOS.map(p => p.category))];
